# Generated by Django 4.0.4 on 2022-05-25 11:36

import carriculum.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('avator', models.ImageField(blank=True, upload_to=carriculum.models.renamesubjectavator, verbose_name='Subject Avator')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='carriculum.standard')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.PositiveSmallIntegerField(verbose_name='Chapter Number:')),
                ('video', models.FileField(blank=True, null=True, upload_to=carriculum.models.renamevideo, verbose_name='Lesson Video')),
                ('presentation', models.FileField(blank=True, null=True, upload_to=carriculum.models.renamepresentation, verbose_name='Lesson presentationj')),
                ('notes', models.FileField(blank=True, null=True, upload_to=carriculum.models.renamenotes, verbose_name='Lesson Notes')),
                ('lesson_id', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 5, 25, 11, 36, 35, 561606, tzinfo=utc))),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='carriculum.subject')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
