# Generated by Django 4.0.4 on 2022-05-28 05:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('carriculum', '0002_alter_lesson_created_at_alter_lesson_lesson_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 28, 5, 20, 26, 497308, tzinfo=utc)),
        ),
    ]
