# Generated by Django 4.0.4 on 2022-05-25 11:36

from django.db import migrations, models
import userinfo.models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profilepic',
            field=models.ImageField(blank=True, upload_to=userinfo.models.renameprofile),
        ),
    ]
